event-handler:
  db-operations-executor:
    core-pool-size: ${DEFAULT_DB_OPERATIONS_CORE_POOL_SIZE:5}
    max-pool-size: ${DEFAULT_DB_OPERATIONS_MAX_POOL_SIZE:10}
    timeout-millis: ${DEFAULT_DB_OPERATIONS_TIMEOUT_MILLIS:30000}
  cpu-operations-executor:
    timeout-millis: ${DEFAULT_CPU_OPERATIONS_TIMEOUT_MILLIS:30000}
  schedule-operations-executor:
    core-pool-size: ${DEFAULT_SCHEDULE_OPERATIONS_CORE_POOL_SIZE:5}
    max-pool-size: ${DEFAULT_SCHEDULE_OPERATIONS_MAX_POOL_SIZE:10}
    timeout-millis: ${DEFAULT_SCHEDULE_OPERATIONS_TIMEOUT_MILLIS:30000}

